models/Message.php
<?php

namespace xolodok\dialog\models;

use Yii;
use xolodok\dialog\Module;
use yii\behaviors\TimestampBehavior;
use yii\web\BadRequestHttpException;

/**
 * This is the model class for table "messages".
 *
 * @property integer $id
 * @property integer $dialog_id
 * @property integer $sender_id
 * @property integer $recipient_id
 * @property integer $read
 * @property string $date
 */
class Message extends \yii\db\ActiveRecord
{
    /**
     * Флаг непрочитанного сообщения
     */
    const UNREAD = 0;

    /**
     * Флаг прочитанного сообщения
     */
    const READ = 1;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'messages';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'date',
                'updatedAtAttribute' => false,
                'value' => function(){ return date('Y-m-d H:i:s');},
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['text'], 'required'],
            [['dialog_id', 'user_id', 'read'], 'integer'],
            [['date'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Module::t('dialog', 'ID'),
            'dialog_id' => Module::t('dialog', 'Dialog ID'),
            'user_id' => Module::t('dialog', 'Sender'),
            'read' => Module::t('dialog', 'Read'),
            'date' => Module::t('dialog', 'Date'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDialog()
    {
        return $this->hasOne(Dialog::className(), ['id' => 'dialog_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(Module::getInstance()->userClass, ['id' => 'user_id']);
    }

    /**
     * Проверка, является ли создатель сообщения текущим юзером
     * @param int $userId Id пользователя
     * @return bool
     */
    public function isSender($userId)
    {
        return $userId == $this->user_id;
    }

    /**
     * Поиск сообщений диалога
     * @param int $id Id диалога
     * @return array Message[]
     */
    public static function findByDialog($id)
    {
        return static::find()
            ->where(['dialog_id' => $id])
            ->all();
    }

    /**
     * Возвращает время создания сообщения
     * @return string
     */
    public function getTime()
    {
        return Yii::$app->formatter->asTime($this->date, 'php:H:i');
    }

    /**
     * Возвращает время создания сообщения
     * @return string
     */
    public function getDateCreated()
    {
        return Yii::$app->formatter->asDate($this->date, 'php:d-m-Y');
    }

    /**
     * Проверка, прочитано ли сообщение
     * @return bool
     */
    public function isRead()
    {
        return $this->read === self::READ;
    }

    public function getFormattedDate()
    {
        return Yii::$app->formatter->asDate($this->date) . ' ' . $this->time;
    }

    public function read()
    {
        $this->updateAttributes(['read' => self::READ]);
    }

    public function beforeSave($insert)
    {
        if(!$this->hasAccess()){
            throw new BadRequestHttpException('You do not have access to a dialogue!');            
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function hasAccess()
    {
        return $this->user_id === $this->dialog->sender_id || $this->user_id === $this->dialog->recipient_id;
    }

    public static function todayExists($dialogId)
    {
        return static::find()
            ->where([
                'dialog_id' => $dialogId,
                'DATE(date)' => date('Y-m-d'),
            ])
            ->exists();
    }

    public function getInterlocuterId()
    {
        return $this->dialog->getInterlocutorId($this->user_id);
    }    
}

models/MessageForm.php
<?php

namespace xolodok\dialog\models;

use Yii;
use yii\base\Model;

class MessageForm extends Model
{
	public $subject;

	public $text;

	public $username;

	public $email;

	public $userId;

	public $captcha;

	public $reCaptcha;

	private $_dialog;

	public function rules()
	{
		return [
			[['subject', 'text', 'email', 'username', 'reCaptcha'], 'required'],
			['email', 'email'],
			[['subject', 'username'], 'string', 'max' => 255],
			['text', 'string'],
			['userId', 'integer'],
			//['captcha', 'captcha', 'captchaAction'=>'dialog/dialog/captcha'],
            ['reCaptcha', \himiklab\yii2\recaptcha\ReCaptchaValidator::className(), 'secret' => '6LfyfzgUAAAAAItJByhurTXM71c9m5zY7eYnIK9i', 'uncheckedMessage' => 'Please confirm that you are not a bot.'],			
		];
	}

	public function createDialog()
	{
		if($this->validate()){
			$this->_dialog = new Dialog();
			$this->_dialog->loadDefaultValues();
			$this->_dialog->setAttributes([
				'email' => $this->email,
				'username' => $this->username,
				'subject' => $this->subject,
				'recipient_id' => $this->userId,
			]);

			if($this->_dialog->save(false)){
				$message = new Message();
				$message->loadDefaultValues();
				$message->text = $this->text;
				$message->link('dialog', $this->_dialog);
			}

			return true;
		}

		return false;
	}
}

controllers/MessageController.php
<?php

namespace xolodok\dialog\controllers;

use Yii;
use yii\web\Response;
use xolodok\dialog\models\Message;
use yii\data\Pagination;
use xolodok\dialog\Module;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;

class MessageController extends \yii\web\Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionCreate()
    {
        $model = new Message();
        $model->loadDefaultValues();
        $model->user_id = Yii::$app->user->id;

        if($model->load(Yii::$app->request->post()) && $model->save()){

            $date = !Message::todayExists($model->dialog_id) ? date('d-m-Y') : false;
            $messageHtml = $this->renderPartial('_message', [
                'message' => $model,
                'date' => $date,
            ]);
            
            if(Module::getInstance()->messageAjax && Yii::$app->request->isAjax){
                Yii::$app->response->format = Response::FORMAT_JSON;

                return [
                    'success' => true,
                    'message' => $messageHtml,
                ];
            }
        }

        return $this->redirect(['view', 'id' => $model->dialog_id]);
    }

    protected function findModel($id)
    {
        if (($model = Message::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }    
}

views/message/_message.php
<?php

use yii\helpers\Html;
?>

<?php if($date !== false) echo Html::tag('h4', $date);?>

<div class="col-md-10">
	<div class="bubble<?= $message->isSender(Yii::$app->user->id) ? ' bubble-alt green' : ''?>">
		<p><?= $message->text?></p>
	</div>
</div>
<div class="col-md-2">
	<p class="message-time"><?= $message->formattedDate?></p>
	<p class="message-time"><?= $message->isRead() ? 'Read' : 'No read'?></p>
</div>

views/message/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
?>
<div class="dialog-form">
	<h1>Create new message</h1>
	
	<?php $form = ActiveForm::begin()?>

	<?= $form->field($model, 'subject')?>

	<?= $form->field($model, 'text')->textarea()?>

	<?= $form->field($model, 'userId')->hiddenInput()->label(false)?>

	<?= Html::submitButton('Send', ['class' => 'btn btn-success btn-block'])?>

	<?php ActiveForm::end()?>

</div>

views/message/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use xolodok\dialog\AssetBundle;

/* @var $this yii\web\View */
AssetBundle::register($this);
?>

<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title"><?= Module::t('dialog', 'Messages')?></h3>
				</div>
				<div class="panel-body">
					<?php if(!empty($dialogs)):?>

						<ul class="media-list">

							<?php foreach($dialogs as $dialog):?>

								<li class="media">
									<a href="<?= Url::to(['view', 'id' => $dialog->id])?>">
										<div class="media-left" href="#">
											
											<?php 
												if($dialog->isGuest()){
													echo \cebe\gravatar\Gravatar::widget([
													    'email' => $dialog->email,
													    'options' => [
													        'alt' => $dialog->username
													    ],
													    'size' => 64
													]);
												}
												else{
													echo Html::img($dialog->getInterlocutor(Yii::$app->user->id)->getAvatar());
												}
											?>

										</div>
										<div class="media-body">
											<h4 class="list-group-item-heading">
												<?= $dialog->subject?>
												<span class="pull-right"><?= $dialog->getSenderName(Yii::$app->user->id)?></span>
											</h4>
											<p class="list-group-item-text">
												<?= $dialog->message->text?>
												<span class="pull-right"><?= $dialog->message->formattedDate?></span>
											</p>
										</div>
									</li>
								</a>

							<?php endforeach?>

						</ul>

					<?php else:?>
						<h2><?= Module::t('dialog', 'Dialogs is Empty')?></h2>
					<?php endif?>
				</div>
			</div>
		</div>
	</div>
</div>